version: '3.8'

services:
  dbmigration:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - dbmigration-db
  dbmigration-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbcode
      - POSTGRES_PASSWORD=dbcode
      - POSTGRES_DB=dbchallenge

volumes:
  postgres_data: